### PR TITLE
update SBT 1.4.2

### PR DESCRIPTION
**Pull request by lemastero**

### CODE REVIEW

**Comment by SethTisue** [comment]
1.4.2 came out today :-)

**Comment by lemastero** [comment]
Would you mind if I ask ScalaSteward to open PR's when new versions will show up?

**Comment by sullis** [comment]
SBT 1.4.4 is the latest version.

**Comment by SethTisue** [comment]
@anatoliykmetyuk there's no reason not to enable Scala Steward here, is there?

**Comment by anatoliykmetyuk** [comment]
Not that I am aware of.

**Comment by sullis** [comment]
+1 for ScalaSteward

**Comment by lemastero** [comment]
This repo should receive all the updates it needs from ScalaSteward :)

**Pull request closed without merging**
