### PR TITLE
Fix a link changed in Scala 3.0.0-RC1 reference

### PR DESCRIPTION
**Pull request by ShapelessCat**

### CODE REVIEW

**Review by Philippus — APPROVED** [review]

**Comment by ShapelessCat** [comment]
The status of this PR look weird.
Even though it's already approved, I still can see the red "Review required" and "Merging is blocked".
Also, in the PR list page https://github.com/scala/scala3-example-project/pulls, I can see this approved PR is marked as " Review required".

**Comment by SethTisue** [comment]
Literally anyone on GitHub can "approve" a PR, but the approval doesn't count towards "Review required" unless the approval is from someone who has merge rights in the repo. In these cases, the checkmark next to the approval shows as gray rather than green.

Philippus has merge rights in many scala/* repos, but not in this one. That probably came about because this repo was transferred here from the lampepfl org.

**Comment by SethTisue** [comment]
@Philippus I have added you to https://github.com/orgs/scala/teams/docs/members, and I've given that team write access to this repo.

I would actually be happy to also add you to https://github.com/orgs/scala/teams/committers if the need ever arises. (For example, if you became more active in the scala/scala repo.)

**Comment by SethTisue** [comment]
thank you @ShapelessCat and @Philippus

**Pull request merged**
